### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by Ppang0405** [Nukesor/pornhub-dl#11]
Run `poetry run alembic stamp head`

Hmm I do not know how to use `SQLAlchemy`, please help.

Logs:
`Traceback (most recent call last):                                                                    
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 509, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/alembic/config.py", line 552, in run_cmd
    fn(
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/alembic/command.py", line 581, in stamp
    script.run_env()
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "migrations/env.py", line 73, in run_migrations_online
    with connectable.connect() as connection:
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection
    return self._wrap_pool_connect(
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 509, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/truongnguyen/Library/Caches/pypoetry/virtualenvs/pornhub-dl-VgIF-CAG-py3.8/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/13/e3q8)`

**Comment by Nukesor** [comment]
Sorry, but this is not the right place to ask questions about how to use libraries and technologies utilized by this project.

Please refer to the official documentations of Sqlalchemy, Alembic and Postgreql.
