### ISSUE TITLE
'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by oikmeg** [Nukesor/pornhub-dl#18]
```
bash-5.1$ poetry run python pornhub-dl user lakindayxo
2022-06-05 15:42:52,612 - INFO - Crawling https://www.pornhub.com/model/lakindayxo/videos
2022-06-05 15:42:53,603 - INFO - Crawling https://www.pornhub.com/model/lakindayxo/videos/upload
Traceback (most recent call last):
  File "/app/pornhub/pornhub-dl", line 7, in <module>
    main()
  File "/app/pornhub/pornhub/__init__.py", line 14, in main
    cli()
  File "/app/pornhub/.venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/app/pornhub/.venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/app/pornhub/.venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/pornhub/.venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/pornhub/.venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/pornhub/pornhub/entry/user.py", line 30, in get_user
    if download_user_videos(session, user):
  File "/app/pornhub/pornhub/extractors/user.py", line 23, in download_user_videos
    video_upload_viewkeys = get_video_upload_viewkeys(user)
  File "/app/pornhub/pornhub/extractors/user.py", line 261, in get_video_upload_viewkeys
    for video in videos.find_all("li"):
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by Nukesor** [comment]
https://github.com/Nukesor/pornhub-dl/issues/16

**Comment by oikmeg** [comment]
The problem is with https://github.com/Nukesor/pornhub-dl/blob/7c1774292134885a08d2580f2bb947195d6384d7/pornhub/extractors/user.py#L248

What was the purpose of this line? I can't find a similar ID in the current HTML from BS. I'm assuming it was used to make an array of each <div> that contained the video <li>?

I've created a basic patch that gets it working, maybe un-optimally, but I don't want to spend too much time working on it.

**Comment by Nukesor** [comment]
The whole logic seems to be bonked.

I actually took a look at the very first actor I encountered on the frontpage and noticed that the URLs the bot is currently crawling don't even exist any longer.

Seems like they removed the `videos/upload` and `videos/public` sites for at least some users.
The site changes their layout and design all the time.


To be honest, I cannot be bothered any longer at this point. I'm just going to archive this repository.

Feel free to start a new fork of your own, but I don't think it makes a lot of sense for me to keep maintaining this.

I'm simply annoyed by this :D
